#!/bin/sh

export XARGO_RUST_SRC=/home/robin/Projects/rust-xtensa/src/
export RUSTC=/home/robin/Projects/rust-xtensa/build/bin/rustc

cargo xbuild --release

# change this for release flashes
BIN_PATH=target/xtensa-esp8266-none-elf/release/esp32

rm $BIN_PATH.bin*

# convert to bin
esptool.py elf2image --flash_mode="dio" --flash_freq "40m" -o $BIN_PATH.bin $BIN_PATH

# flash
esptool.py --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x0000 $BIN_PATH.bin0x00000.bin